repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-toml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

      # check for file bigger than 500kb
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/find-trailing-comma
    rev: v0.0.1
    hooks:
      - id: find-trailing-comma

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        require_serial: false
        language: python
        types: [python]
        args: ['--config=setup.cfg']

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        require_serial: true
        language: python
        types: [python]
        args: ['--py36-plus',]

      - id: autoflake
        name: autoflake
        entry: autoflake
        require_serial: true
        language: python
        types: [python]
        args: ['--in-place',
               '--remove-unused-variables',
               '--remove-all-unused-imports']

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]

      - id: yapf
        name: yapf
        entry: yapf -i
        require_serial: true
        language: python
        types: [python]
